num1=int(input("enter first number"))
num2=int(input("enter second number"))
add=num1+num2
sub=num1-num2
mul=num1*num2
div=num1/num2
print(f'addition of {num1}+{num2}={add}')
print(f'subtraction of {num1}-{num2}={sub}')
print(f'multiplication of {num1}*{num2}={mul}')
print(f'division of {num1}/{num2}={div}')
